id = "mcp-server-gitlab"
name = "GitLab MCP Server"
description = "Model Context Protocol Server for GitLab"
version = "0.0.2"
schema_version = 1
authors = ["Akbxr <hi@akbxr.com>"]
repository = "https://github.com/akbxr/gitlab-mcp-zed"

[context_servers.mcp-server-gitlab]
name = "GitLab MCP Server"
